from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def listing_reference(): return f'SP-L-{uuid.uuid4().hex[:8].upper()}'
def reservation_reference(): return f'SP-R-{uuid.uuid4().hex[:8].upper()}'
def pickup_reference(): return f'PU-{uuid.uuid4().hex[:8].upper()}'

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='Organization', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=180)),('organization_type',models.CharField(choices=[('RESTAURANT','Restaurant'),('BAKERY','Bakery'),('HOTEL','Hotel'),('SUPERMARKET','Supermarket'),('CATERER','Caterer'),('EVENT_ORGANIZER','Event Organizer'),('NGO','NGO'),('SHELTER','Shelter'),('COMMUNITY_KITCHEN','Community Kitchen'),('OTHER','Other')],max_length=30)),('description',models.TextField(blank=True)),('contact_person',models.CharField(max_length=120)),('email',models.EmailField(max_length=254)),('phone',models.CharField(blank=True,max_length=30)),('operating_hours',models.CharField(blank=True,max_length=255)),('maximum_daily_capacity',models.PositiveIntegerField(blank=True,null=True)),('verification_status',models.CharField(choices=[('PENDING','Pending'),('APPROVED','Approved'),('REJECTED','Rejected'),('SUSPENDED','Suspended')],default='PENDING',max_length=15)),('active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name='FoodCategory', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=80,unique=True)),('active',models.BooleanField(default=True))]),
        migrations.CreateModel(name='Membership', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('role',models.CharField(choices=[('FOOD_PARTNER','Food Partner'),('RECIPIENT','Recipient Organization'),('COURIER','Courier'),('ADMIN','Admin')],max_length=30)),('organization',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='members',to='core.organization')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='memberships',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='Address', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('label',models.CharField(default='Primary',max_length=80)),('line1',models.CharField(max_length=200)),('line2',models.CharField(blank=True,max_length=200)),('city',models.CharField(max_length=100)),('state',models.CharField(max_length=100)),('postal_code',models.CharField(max_length=20)),('latitude',models.DecimalField(blank=True,decimal_places=6,max_digits=9,null=True)),('longitude',models.DecimalField(blank=True,decimal_places=6,max_digits=9,null=True)),('is_primary',models.BooleanField(default=False)),('organization',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='addresses',to='core.organization'))]),
        migrations.CreateModel(name='FoodListing', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('reference',models.CharField(default=listing_reference,max_length=30,unique=True)),('name',models.CharField(max_length=160)),('description',models.TextField(blank=True)),('quantity_listed',models.PositiveIntegerField()),('quantity_reserved',models.PositiveIntegerField(default=0)),('quantity_collected',models.PositiveIntegerField(default=0)),('unit',models.CharField(choices=[('PORTIONS','Portions'),('KILOGRAMS','Kilograms'),('BOXES','Boxes'),('TRAYS','Trays'),('PACKS','Packs')],max_length=15)),('servings',models.PositiveIntegerField(default=1)),('preparation_at',models.DateTimeField()),('available_from',models.DateTimeField()),('available_until',models.DateTimeField()),('storage_condition',models.CharField(choices=[('AMBIENT','Ambient'),('REFRIGERATED','Refrigerated'),('FROZEN','Frozen'),('HOT_HOLD','Hot hold'),('OTHER','Other')],max_length=20)),('ingredients',models.TextField(blank=True)),('allergens',models.TextField(blank=True)),('handling_instructions',models.TextField(blank=True)),('status',models.CharField(choices=[('DRAFT','Draft'),('PUBLISHED','Published'),('PARTIAL','Partially Reserved'),('FULL','Fully Reserved'),('PICKUP','Pickup Scheduled'),('COLLECTED','Collected'),('DELIVERED','Delivered'),('COMPLETED','Completed'),('CANCELLED','Cancelled'),('EXPIRED','Expired'),('REJECTED','Rejected'),('DISPUTED','Disputed')],default='DRAFT',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('category',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='listings',to='core.foodcategory')),('organization',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='listings',to='core.organization'))]),
        migrations.CreateModel(name='Reservation', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('reference',models.CharField(default=reservation_reference,max_length=30,unique=True)),('quantity',models.PositiveIntegerField()),('status',models.CharField(choices=[('REQUESTED','Requested'),('ACCEPTED','Accepted'),('PICKUP','Pickup Scheduled'),('COLLECTED','Collected'),('RECEIVED','Received'),('COMPLETED','Completed'),('CANCELLED','Cancelled'),('REJECTED','Rejected')],default='REQUESTED',max_length=20)),('collection_window_start',models.DateTimeField()),('collection_window_end',models.DateTimeField()),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('listing',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='reservations',to='core.foodlisting')),('organization',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='reservations',to='core.organization')),('requested_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='Courier', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('vehicle_details',models.CharField(blank=True,max_length=160)),('active',models.BooleanField(default=True)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='courier_profile',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='Pickup', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('reference',models.CharField(default=pickup_reference,max_length=30,unique=True)),('status',models.CharField(choices=[('ASSIGNED','Assigned'),('ACCEPTED','Accepted'),('EN_ROUTE','En Route'),('ARRIVED','Arrived'),('COLLECTED','Collected'),('DELIVERED','Delivered'),('COMPLETED','Completed'),('CANCELLED','Cancelled'),('ISSUE','Issue Reported'),('RESCHEDULED','Rescheduled')],default='ASSIGNED',max_length=20)),('window_start',models.DateTimeField()),('window_end',models.DateTimeField()),('expected_quantity',models.PositiveIntegerField()),('collected_quantity',models.PositiveIntegerField(blank=True,null=True)),('delivered_quantity',models.PositiveIntegerField(blank=True,null=True)),('collection_at',models.DateTimeField(blank=True,null=True)),('delivery_at',models.DateTimeField(blank=True,null=True)),('collection_notes',models.TextField(blank=True)),('delivery_notes',models.TextField(blank=True)),('issue_notes',models.TextField(blank=True)),('updated_at',models.DateTimeField(auto_now=True)),('courier',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='pickups',to='core.courier')),('destination',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='incoming_pickups',to='core.organization')),('reservation',models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,related_name='pickup',to='core.reservation')),('source',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='outgoing_pickups',to='core.organization'))]),
        migrations.CreateModel(name='PickupStatusHistory', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('from_status',models.CharField(blank=True,max_length=20)),('to_status',models.CharField(max_length=20)),('note',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('changed_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),('pickup',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='status_history',to='core.pickup'))]),
        migrations.CreateModel(name='DeliveryConfirmation', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('received_by',models.CharField(blank=True,max_length=120)),('received_quantity',models.PositiveIntegerField()),('condition',models.CharField(default='GOOD',max_length=30)),('notes',models.TextField(blank=True)),('confirmed_at',models.DateTimeField())),('pickup',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='delivery_confirmation',to='core.pickup'))]),
        migrations.CreateModel(name='Notification', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=180)),('message',models.TextField()),('related_type',models.CharField(blank=True,max_length=50)),('related_id',models.CharField(blank=True,max_length=64)),('read_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='notifications',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='ImpactRecord', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('portions',models.PositiveIntegerField()),('weight_kg',models.DecimalField(blank=True,decimal_places=2,max_digits=10,null=True)),('recorded_at',models.DateTimeField(auto_now_add=True)),('organization',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,to='core.organization')),('pickup',models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,to='core.pickup'))]),
        migrations.CreateModel(name='AuditLog', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('action',models.CharField(max_length=120)),('entity_type',models.CharField(max_length=80)),('entity_id',models.CharField(max_length=64)),('details',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('actor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='FoodSafetyRecord', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('preparation_timestamp',models.DateTimeField()),('best_before_timestamp',models.DateTimeField(blank=True,null=True)),('storage_method',models.CharField(max_length=120)),('temperature_c',models.DecimalField(blank=True,decimal_places=2,max_digits=5,null=True)),('allergen_information',models.TextField(blank=True)),('handling_notes',models.TextField(blank=True)),('listing',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='safety',to='core.foodlisting'))]),
        migrations.CreateModel(name='Complaint', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('category',models.CharField(max_length=80)),('description',models.TextField()),('evidence',models.FileField(blank=True,upload_to='complaints/')),('admin_response',models.TextField(blank=True)),('resolution',models.TextField(blank=True)),('status',models.CharField(choices=[('OPEN','Open'),('IN_REVIEW','Under Review'),('ACTION_REQUIRED','Action Required'),('RESOLVED','Resolved')],default='OPEN',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('organization',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,to='core.organization')),('pickup',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,to='core.pickup')),('reporter',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to=settings.AUTH_USER_MODEL)),('reservation',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,to='core.reservation'))]),
        migrations.CreateModel(name='SavedFood', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=160)),('description',models.TextField(blank=True)),('unit',models.CharField(choices=[('PORTIONS','Portions'),('KILOGRAMS','Kilograms'),('BOXES','Boxes'),('TRAYS','Trays'),('PACKS','Packs')],max_length=15)),('servings',models.PositiveIntegerField(default=1)),('ingredients',models.TextField(blank=True)),('allergens',models.TextField(blank=True)),('storage_condition',models.CharField(blank=True,choices=[('AMBIENT','Ambient'),('REFRIGERATED','Refrigerated'),('FROZEN','Frozen'),('HOT_HOLD','Hot hold'),('OTHER','Other')],max_length=20)),('category',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='core.foodcategory')),('organization',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='saved_foods',to='core.organization'))]),
        migrations.AddConstraint(model_name='membership',constraint=models.UniqueConstraint(fields=('user','organization'),name='unique_membership')),
        migrations.AddConstraint(model_name='savedfood',constraint=models.UniqueConstraint(fields=('organization','name'),name='unique_saved_food')),
        migrations.AddIndex(model_name='foodlisting',index=models.Index(fields=('status','available_until'),name='core_foodli_status_9f1e2a_idx')),
        migrations.AddIndex(model_name='foodlisting',index=models.Index(fields=('organization','status'),name='core_foodli_organiz_efc0b6_idx')),
        migrations.AddIndex(model_name='foodlisting',index=models.Index(fields=('category','status'),name='core_foodli_categor_6e9d6d_idx')),
        migrations.AddIndex(model_name='reservation',index=models.Index(fields=('listing','status'),name='core_reserva_listin_8c4d7a_idx')),
        migrations.AddIndex(model_name='reservation',index=models.Index(fields=('organization','status'),name='core_reserva_organi_6f2b8c_idx')),
        migrations.AddIndex(model_name='pickup',index=models.Index(fields=('status','window_start'),name='core_pickup_status_7e3d91_idx')),
        migrations.AddIndex(model_name='pickup',index=models.Index(fields=('courier','status'),name='core_pickup_courie_9a6d12_idx')),
        migrations.AddIndex(model_name='notification',index=models.Index(fields=('user','read_at','created_at'),name='core_notifi_user_re_6d5a22_idx')),
        migrations.AddIndex(model_name='auditlog',index=models.Index(fields=('entity_type','entity_id'),name='core_auditl_entity__4b2c31_idx')),
        migrations.AddIndex(model_name='auditlog',index=models.Index(fields=('created_at',),name='core_auditl_created_8f1a11_idx')),
    ]
