import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { requireUser } from '@/lib/guards';
import { assertPickupTransition } from '@/lib/pickup-workflow';
import { PickupStatus, Role } from '@prisma/client';

export async function GET() { try { const { user, role, organizationId }=await requireUser([Role.COURIER,Role.FOOD_PARTNER,Role.RECIPIENT_ORGANIZATION,Role.ADMIN]); const where:any=role===Role.COURIER?{assignments:{some:{courier:{userId:user.id}}}}:role===Role.ADMIN?{}:{OR:[{sourceOrganizationId:organizationId},{destinationOrganizationId:organizationId}]}; const data=await db.pickupRequest.findMany({where,include:{reservation:{include:{listing:{include:{category:true}}}},sourceOrganization:{include:{addresses:true}},destinationOrganization:{include:{addresses:true}},assignments:{include:{courier:{include:{user:true}}}},statusHistory:{orderBy:{createdAt:'asc'}},delivery:true},orderBy:{windowStart:'asc'},take:100}); return NextResponse.json({data}); } catch(e){return NextResponse.json({error:'You do not have access to these pickups.'},{status:e instanceof Error&&e.message==='UNAUTHENTICATED'?401:403});} }

export async function PATCH(req:Request){try{
 const {user,role}=await requireUser([Role.COURIER,Role.FOOD_PARTNER,Role.RECIPIENT_ORGANIZATION,Role.ADMIN]); const body=await req.json(); const id=String(body.id||''); const to=String(body.status||'') as PickupStatus; const pickup=await db.pickupRequest.findUnique({where:{id},include:{assignments:{include:{courier:true}},reservation:{include:{listing:true}}}}); if(!pickup)return NextResponse.json({error:'Pickup not found.'},{status:404}); if(role===Role.COURIER&&!pickup.assignments.some(a=>a.courier.userId===user.id))return NextResponse.json({error:'This pickup is not assigned to you.'},{status:403}); assertPickupTransition(pickup.status,to); const now=new Date(); const data:any={status:to};
 if(to==='COLLECTED'){const qty=Number(body.collectedQuantity);if(!Number.isInteger(qty)||qty<=0||qty>pickup.reservation.quantity)return NextResponse.json({error:`Collected quantity must be between 1 and ${pickup.reservation.quantity}.`},{status:400});data.collectedQuantity=qty;data.collectionAt=now;data.collectionNotes=body.notes?String(body.notes):null;data.collectionPhotoUrl=body.photoUrl?String(body.photoUrl):null;}
 if(to==='DELIVERED'){const qty=Number(body.receivedQuantity??pickup.collectedQuantity??0);if(!Number.isInteger(qty)||qty<0||qty>(pickup.collectedQuantity??0))return NextResponse.json({error:'Received quantity cannot exceed the collected quantity.'},{status:400});data.deliveredQuantity=qty;data.deliveryAt=now;data.deliveryCondition=body.condition||'GOOD';data.deliveryPhotoUrl=body.photoUrl?String(body.photoUrl):null;}
 const updated=await db.$transaction(async tx=>{const result=await tx.pickupRequest.update({where:{id},data});await tx.pickupStatusHistory.create({data:{pickupId:id,fromStatus:pickup.status,toStatus:to,changedByUserId:user.id,note:body.note?String(body.note):undefined}});
  if(to==='ACCEPTED')await tx.pickupAssignment.updateMany({where:{pickupId:id,courier:{userId:user.id}},data:{acceptedAt:now}});
  if(to==='COLLECTED'){await tx.reservation.update({where:{id:pickup.reservationId},data:{status:'COLLECTED'}});const listed=pickup.reservation.listing;const qty=Number(data.collectedQuantity);const collected=listed.quantityCollected+qty;const reserved=Math.max(0,listed.quantityReserved-qty);await tx.foodListing.update({where:{id:listed.id},data:{quantityCollected:collected,quantityReserved:reserved,status:'COLLECTED'}});}
  if(to==='DELIVERED'){await tx.deliveryConfirmation.upsert({where:{pickupId:id},update:{deliveredAt:now,receivedQuantity:data.deliveredQuantity,condition:data.deliveryCondition,notes:body.notes?String(body.notes):null,proofPhotoUrl:body.photoUrl?String(body.photoUrl):null},create:{pickupId:id,collectedAt:pickup.collectionAt,deliveredAt:now,receivedQuantity:data.deliveredQuantity,condition:data.deliveryCondition,notes:body.notes?String(body.notes):null,proofPhotoUrl:body.photoUrl?String(body.photoUrl):null}});await tx.reservation.update({where:{id:pickup.reservationId},data:{status:'RECEIVED'}});await tx.foodListing.update({where:{id:pickup.reservation.listing.id},data:{status:'DELIVERED'}});}
  if(to==='COMPLETED'){const received=pickup.deliveredQuantity??pickup.collectedQuantity??0;await tx.reservation.update({where:{id:pickup.reservationId},data:{status:'COMPLETED'}});await tx.foodListing.update({where:{id:pickup.reservation.listing.id},data:{status:'COMPLETED'}});await tx.impactRecord.upsert({where:{pickupId:id},update:{portions:received,reservationId:pickup.reservationId,organizationId:pickup.sourceOrganizationId},create:{pickupId:id,reservationId:pickup.reservationId,portions:received,organizationId:pickup.sourceOrganizationId}});}
  const members=await tx.organizationMember.findMany({where:{organizationId:{in:[pickup.sourceOrganizationId,pickup.destinationOrganizationId]}},select:{userId:true}});if(members.length)await tx.notification.createMany({data:members.map(m=>({userId:m.userId,type:'PICKUP_STATUS',title:`Pickup ${to.replaceAll('_',' ').toLowerCase()}`,message:`Pickup ${pickup.reference} is now ${to.replaceAll('_',' ').toLowerCase()}.`,relatedEntityType:'PICKUP',relatedEntityId:id}))});await tx.auditLog.create({data:{userId:user.id,action:'PICKUP_STATUS_CHANGED',entityType:'PICKUP',entityId:id,details:{from:pickup.status,to}}});return result;});return NextResponse.json({data:updated});
 }catch(e){const message=e instanceof Error?e.message:'We could not update this pickup.';return NextResponse.json({error:message.includes('Invalid pickup')?message:'We could not update this pickup.'},{status:400});}}
